name: Zones
main: com.zones.Zones
version: 3.0b3
author: 'Meaglin'
authors: [ 'Mysteryman', 'GunterDW' ]
depend: [ 'Vault' ]
softdepend: [ 'WorldGuard', 'WorldEdit', 'VirtualPlayers' ] 
website: https://github.com/Meaglin/Zones
description: >
             Area protection plugin, including following features:
              * Grief protection(block fire, lava, etc...)
              * Easy of use(allow users to manage their own area)
commands: