name: Zones
main: com.zones.Zones
version: 1.1
author: Meaglin
website: https://github.com/Meaglin/0xFFFF
commands:
    zhelp
    zcreate
    zimport
    zadd
    zremove
    zsetplot
    zsetheight
    zsetdepth
    zsave
    zconfirm
    zsetz
    zstop
    zsetuser
    zsetgroup
    zaddadmin
    zremoveadmin
    zselect
    zsettype
    zregion
    zgetaccess
    zdelete
    zsetname
    ztogglehealth
    ztoggledynamite
    ztogglelava
    ztogglewater
    ztogglemobs
    ztoggleanimals
    zedit
    zmerge
    zreload
    ztoggle