name: Zones
main: com.zones.Zones
version: 3.0b1
authors: [ 'Meaglin', 'Mysteryman', 'GunterDW' ]
softdepend: [ 'EasyBind' ] 
website: https://github.com/Meaglin/Zones
description: The Over optimized Area Protection tool with integrated Anti Grief options.
commands:
     